ALTER TYPE doc_type ADD VALUE IF NOT EXISTS 'ctps';
ALTER TYPE doc_type ADD VALUE IF NOT EXISTS 'contrato';
ALTER TYPE doc_type ADD VALUE IF NOT EXISTS 'cct';
ALTER TYPE doc_type ADD VALUE IF NOT EXISTS 'fgts';
ALTER TYPE doc_type ADD VALUE IF NOT EXISTS 'ponto';